// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9J8K7M3N5P9Q2R4S6T8U0V2W4X6Y8Z0A2',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'stok-takip-app-12345',
    authDomain: 'stok-takip-app-12345.firebaseapp.com',
    storageBucket: 'stok-takip-app-12345.appspot.com',
    measurementId: 'G-ABCDEFGHIJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGfd1ERgskHZFv_3a9_dy_juxxaX62d2Q',
    appId: '1:1216012110:android:ec4b52b89b0b662a4cc81f',
    messagingSenderId: '1216012110',
    projectId: 'stoktakip11',
    storageBucket: 'stoktakip11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASAQd14IvY38_YPFP0QNn7i1wj7wzZpMU',
    appId: '1:1216012110:ios:231813777a9a1d024cc81f',
    messagingSenderId: '1216012110',
    projectId: 'stoktakip11',
    storageBucket: 'stoktakip11.firebasestorage.app',
    iosBundleId: 'com.example.stoktakip1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7F8G9H0I1J2K3L4M5N6O7P8Q9R0S1T2U3',
    appId: '1:123456789012:macos:0123456789abcdef0123456',
    messagingSenderId: '123456789012',
    projectId: 'stok-takip-app-12345',
    storageBucket: 'stok-takip-app-12345.appspot.com',
    iosBundleId: 'com.example.stokTakipApp',
  );
}
